apiVersion: v1
kind: Service
metadata:
  namespace: raagtime
  name: web
  labels:
    app: raagtime
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: raagtime
  type: ClusterIP
