name: Repository Dispatch

on:
  repository_dispatch:
    types:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Patch the deployment.yaml with new image tag
        run: |
          app=${{ github.event.client_payload.application }}
          image=${{ github.event.client_payload.image }}
          sed -E "s|image: .*$|image: ${image}|g" ${app}/deployment.yaml > tmp.yaml && mv tmp.yaml ${app}/deployment.yaml

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.0
        with:
          message: '${{ github.event.client_payload.application }}: deploy ${{ github.event.client_payload.image }}'
