name: Repository Dispatch

on:
  repository_dispatch:
    types:
      - deploy

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Print the payload
        run: 'echo "Application: ${{ github.event.client_payload.application }}\nImage: ${{ github.event.client_payload.image }}"'